# Generated by Django 2.2a1 on 2019-03-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed_survey',
        ),
    ]
