# Generated by Django 2.2a1 on 2019-04-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_veci_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='veci',
            name='typ',
            field=models.CharField(default='', max_length=15),
        ),
    ]
