# Generated by Django 2.2a1 on 2019-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_veci_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veci',
            name='popis',
            field=models.TextField(default=''),
        ),
    ]
