# Generated by Django 2.2a1 on 2019-04-14 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190413_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.User')),
            ],
        ),
    ]
